import numpy as np
from sklearn.cluster import DBSCAN, KMeans
from shapely.ops import nearest_points
import networkx as nx
from shapely.strtree import STRtree
import logging

logger = logging.getLogger(__name__)

""" Functions for DBSCAN clustering """

def polygon_distance(polygon1, polygon2):
    """
    Calculate the minimum distance between two polygons.

    This function finds the nearest points between two input polygons and 
    returns the Euclidean distance between these points.

    Parameters
    ----------
    polygon1 : shapely.geometry.Polygon
        The first polygon.
    polygon2 : shapely.geometry.Polygon
        The second polygon.

    Returns
    -------
    float
        The minimum distance between polygon1 and polygon2.
    """
    point1, point2 = nearest_points(polygon1, polygon2)
    return point1.distance(point2)


def compute_distance_matrix(polygons):
    """
    Create a distance matrix for a list of polygons.

    This function computes a symmetric matrix where each element [i, j] is the
    minimum distance between the i-th and j-th polygon from the provided list.
    
    Parameters
    ----------
    polygons : list of shapely.geometry.Polygon
        A list of polygons for which to compute pairwise distances.

    Returns
    -------
    numpy.ndarray
        A 2D array representing the distance matrix between the polygons.
    """
    num_polygons = len(polygons)
    distance_matrix = np.zeros((num_polygons, num_polygons))
    
    for i in range(num_polygons):
        for j in range(i + 1, num_polygons):
            distance = polygon_distance(polygons[i], polygons[j])
            distance_matrix[i, j] = distance
            distance_matrix[j, i] = distance  # Ensure symmetry
    
    return distance_matrix


def build_multistep_owner_clusters(df, min_samples, eps):
    """
    Build clusters for same-owner parcels using a multi-step approach.

    This function computes the distance matrix for parcels in a GeoDataFrame and then 
    clusters them using DBSCAN. If all distances are zero (i.e., parcels are touching), 
    the epsilon value is set to 1 to enable clustering. For datasets with fewer than three 
    parcels, no clustering is performed.

    Parameters
    ----------
    df : geopandas.GeoDataFrame
        GeoDataFrame containing parcel data. Must include a 'geometry' column.
    min_samples : int
        The minimum number of samples required for a cluster as passed to DBSCAN.
    eps : float
        The maximum distance between two samples for one to be considered as in the neighborhood of the other.

    Returns
    -------
    numpy.ndarray
        The cluster labels assigned by DBSCAN. Returns an empty array if there are fewer than three parcels.
    """
    polygons = df.geometry.to_list()
    distance_matrix = compute_distance_matrix(polygons)

    # Adjust epsilon if all pairwise distances are zero
    if np.all(distance_matrix == 0):
        eps = 1

    # If there are less than three parcels, skip clustering
    if distance_matrix.shape[0] < 3:
        return np.array([])  # No clustering for very small datasets
    else:
        return build_dbscan_clusters(distance_matrix, min_samples, eps)


def build_owner_clusters(df, min_samples, eps):
    """
    Build clusters for same-owner parcels using DBSCAN clustering.

    This function extracts polygon geometries from the GeoDataFrame, computes the pairwise 
    distance matrix, adjusts the epsilon if needed, and clusters the parcels with DBSCAN. 
    It is designed to cluster parcels that belong to the same owner within a region.

    Parameters
    ----------
    df : geopandas.GeoDataFrame
        A GeoDataFrame containing parcel data with a 'geometry' column.
    min_samples : int
        The minimum number of samples required for a cluster in DBSCAN.
    eps : float
        The distance threshold parameter for DBSCAN.

    Returns
    -------
    numpy.ndarray
        Cluster labels generated by DBSCAN. If fewer than three parcels exist, returns an empty array.
    """
    polygons = df.geometry.to_list()
    distance_matrix = compute_distance_matrix(polygons)

    # Adjust epsilon if all distances are zero
    if np.all(distance_matrix == 0):
        eps = 1

    # If there are less than three parcels, clustering is not performed
    if distance_matrix.shape[0] < 3:
        return np.array([])  # No clustering
    else:
        labels = build_dbscan_clusters(distance_matrix, min_samples, eps)

    # Assign cluster labels to the GeoDataFrame
    df['cluster'] = labels
    df = df[df['cluster'] != -1]  # Drop noise points
    return df


def build_dbscan_clusters(dmatrix, min_samples, eps):
    """
    Build DBSCAN clusters from a distance matrix.

    This function applies the DBSCAN clustering algorithm using a precomputed distance matrix.

    Parameters
    ----------
    dmatrix : numpy.ndarray
        A precomputed distance matrix.
    min_samples : int
        The minimum number of samples required to form a cluster in DBSCAN.
    eps : float
        The epsilon parameter (maximum distance for neighborhood).

    Returns
    -------
    numpy.ndarray
        An array of cluster labels corresponding to the input data.
    """
    dbscan = DBSCAN(eps=eps, min_samples=min_samples, metric='precomputed')
    return dbscan.fit_predict(dmatrix)

""" Sindex Optimization for Clustering """
def build_sindex_owner_clusters(df, sample_size, threshold):
    df = df.reset_index(drop=True)
    polygons = list(df.geometry)
    n = len(polygons)
    
    # Build a mapping from geometry identity to index for quick lookup.
    idx_map = {idx: poly for idx, poly in enumerate(polygons)}
    
    # Build an STRtree for all the polygons.
    tree = STRtree(polygons)

    # Initialize a graph where each node represents a polygon.
    G = nx.Graph()
    G.add_nodes_from(range(n))

    # For each polygon, query candidates using a buffered envelope.
    for i, poly in enumerate(polygons):
       
        search_box = poly.envelope.buffer(threshold)
        # Expand the polygon’s envelope by the threshold to get candidate neighbors.
        candidates = tree.query(search_box, predicate='intersects',)
        # drop self-matches
        candidates = [int(c) for c in candidates if c != i]
        if len(candidates) + 1 < sample_size:
            continue 
     
        for candidate_id in candidates:
            # Only consider each pair once.
            if i < candidate_id:
                # Compute the actual distance.
                d = poly.distance(idx_map[candidate_id])
                if d <= threshold:
                    G.add_edge(int(i), int(candidate_id))
                
    # Extract clusters as connected components of the graph.
    clusters = [list(component) for component in nx.connected_components(G) if len(component) > 1]
    
    if len(clusters) == 0:
        return None
    
    cluster_map = {}
    for cluster_id, cluster in enumerate(clusters):
        for idx in cluster:
            cluster_map[idx] = int(cluster_id)
    
    df['cluster'] = df.index.map(cluster_map)

    # drop -1 clusters
    df = df[df['cluster'].notnull()]

    return df



def spatial_dbscan(df, sample_size, threshold):
    df = df.reset_index(drop=True)
    polygons = list(df.geometry)
    n = len(polygons)

    tree = STRtree(polygons)
    labels = np.full(n, -1)  # Start with -1 (noise)
    visited = np.zeros(n, dtype=bool)
    cluster_id = 0

    idx_map = {idx: poly for idx, poly in enumerate(polygons)}

    def region_query(i):
        # Use STRtree to get candidate neighbors
        search_box = polygons[i].envelope.buffer(threshold)
        candidates = tree.query(search_box, predicate='intersects')
        # Filter by true distance
        neighbors = [
            c for c in candidates 
            if polygons[i].distance(idx_map[c]) <= threshold
        ]
        return neighbors

    for i in range(n):
        if visited[i]:
            continue
        visited[i] = True
        neighbors = region_query(i)

        if len(neighbors) < sample_size:
            labels[i] = -1  # noise
        else:
            labels[i] = cluster_id
            seeds = neighbors.copy()
            seeds.remove(i) if i in seeds else None
            while seeds:
                j = seeds.pop()
                if not visited[j]:
                    visited[j] = True
                    j_neighbors = region_query(j)
                    if len(j_neighbors) >= sample_size:
                        for k in j_neighbors:
                            if k not in seeds:
                                seeds.append(k)
                if labels[j] == -1:
                    labels[j] = cluster_id  # turn noise into border
                if labels[j] == -1 or labels[j] is None:
                    labels[j] = cluster_id
            cluster_id += 1

    df['cluster'] = labels
    df = df[df['cluster'] != -1]  # drop noise
    return df


""" Functions for KMeans clustering """

def build_place_regions(df, max_parcels_per_cluster):
    """
    Assign each parcel to a region using KMeans clustering.

    This function partitions parcels into regions such that each region contains a maximum 
    number of parcels specified by max_parcels_per_cluster. It uses the centroids of parcel 
    geometries to perform clustering.

    Parameters
    ----------
    df : geopandas.GeoDataFrame
        A GeoDataFrame containing parcel data with a 'geometry' column.
    max_parcels_per_cluster : int
        The maximum number of parcels that should be assigned to a single cluster/region.

    Returns
    -------
    tuple
        A tuple containing:
          - labels : numpy.ndarray of region labels for each parcel.
          - centroids : numpy.ndarray containing the centroid coordinates of each region.
    """
    # Determine number of clusters based on the number of parcels
    nclusters = 1 if len(df) < max_parcels_per_cluster else len(df) // max_parcels_per_cluster
    
    coords = build_coords(df)
    labels, centroids = build_kmeans_clusters(nclusters, coords)
    return labels, centroids


def build_kmeans_clusters(n_clusters, coords):
    """
    Perform KMeans clustering on coordinate data.

    This function applies KMeans clustering to the provided coordinates.

    Parameters
    ----------
    n_clusters : int
        The number of clusters to form.
    coords : list of tuple
        A list of coordinate pairs (x, y) representing parcel centroids.

    Returns
    -------
    tuple
        A tuple containing:
          - labels : numpy.ndarray of cluster labels for each input coordinate.
          - centroids : numpy.ndarray containing the coordinates of the cluster centroids.
    """
    kmeans = KMeans(n_clusters=n_clusters, random_state=42)
    labels = kmeans.fit_predict(coords)
    centroids = kmeans.cluster_centers_
    return labels, centroids


def build_coords(df):
    """
    Extract centroid coordinates from a GeoDataFrame.

    This function computes the centroids of parcel geometries and returns their coordinates.

    Parameters
    ----------
    df : geopandas.GeoDataFrame
        A GeoDataFrame with a 'geometry' column containing the geometries of parcels.

    Returns
    -------
    list of tuple
        A list of (x, y) coordinate pairs representing the centroids of each parcel.
    """
    return list(zip(df.centroid.x, df.centroid.y))
